---

  - name: PLAY 1 - IOSのファクト情報を収集
    hosts: iosxe
    gather_facts: no

    tasks:

      - name: IOSのファクト情報を収集
        cisco.ios.ios_facts:
      
      - name: OSバージョンのデバッグ
        debug:
          var: ansible_net_version

      - name: ホスト名のデバッグ
        debug:
          var: ansible_net_hostname